# 旧架构随机初始化
model_name_or_path: null
config_name: models/gte-old-scratch
tokenizer_name: models/gte-large-en-v1.5
train_file: data/imdb/train.csv
validation_files: data/imdb/val.csv
text_column_names: sentence
output_dir: output/gte_old_scratch

learning_rate: 2e-5
num_train_epochs: 1
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
max_seq_length: 256
metric_name: accuracy

do_train: true
do_eval: true
eval_strategy: steps
eval_steps: 500
save_strategy: "no"
logging_steps: 100
report_to: none
trust_remote_code: true
fp16: true
gradient_checkpointing: true
